INSERT INTO metadata_catalog (
    dataset_name,
    dataset_type,
    source_name,
    storage_location,
    row_count,
    columns_summary,
    description
)
VALUES
    ('심평원 요양기관 개설 현황 원천 CSV',
     '원천 파일',
     '공공데이터포털',
     'data/raw/hira/hira_institution_open_status_2025_12_31.csv',
     104775,
     '암호화된요양기호, 요양기관명, 요양종별, 시도명, 시군구명, 도로명주소, 표시과목명, 개설일자',
     '공공데이터포털에서 받은 요양기관 개설 현황 원본 데이터'),
    ('심평원 요양기관 개설 현황 샘플 CSV',
     '샘플 파일',
     '공공데이터포털',
     'data/processed/hira/hira_institution_open_status_sample_1000_h2.csv',
     1000,
     '암호화된요양기호, 요양기관명, 요양종별, 시도명, 시군구명, 도로명주소, 표시과목명, 개설일자',
     '화면 시연과 로컬 테스트를 위한 1,000건 샘플 데이터'),
    ('요양기관 개설 현황 테이블',
     '원천 샘플 테이블',
     'H2',
     'hira_institution_sample',
     1000,
     'sample_id, encrypted_provider_id, institution_name, institution_type, sido_name, sigungu_name, road_address, specialty_name, opened_date',
     '샘플 CSV를 H2에 실제 적재한 원천 샘플 테이블');

INSERT INTO lineage_flow (
    source_name,
    source_type,
    target_name,
    target_type,
    process_name,
    transform_type,
    description,
    sort_order
)
VALUES
    ('공공데이터포털',
     'SOURCE',
     '심평원 요양기관 개설 현황 원천 CSV',
     'FILE',
     '파일 다운로드',
     'DOWNLOAD',
     '공공데이터포털에서 심평원 요양기관 개설 현황 CSV를 다운로드한다.',
     1),
    ('심평원 요양기관 개설 현황 원천 CSV',
     'FILE',
     '심평원 요양기관 개설 현황 샘플 CSV',
     'FILE',
     '인코딩 변환 및 샘플 추출',
     'TRANSFORM',
     'CP949 원본을 UTF-8로 변환하고 상위 1,000건만 추출한다.',
     2),
    ('심평원 요양기관 개설 현황 샘플 CSV',
     'FILE',
     '요양기관 개설 현황 테이블',
     'TABLE',
     '테이블 적재',
     'LOAD',
     'CSV 컬럼을 화면에서 쓰기 쉬운 영문 물리 컬럼으로 매핑해 H2 테이블에 실제 적재한다.',
     3),
    ('요양기관 개설 현황 테이블',
     'TABLE',
     '메타데이터/리니지 샘플 화면',
     'SCREEN',
     '화면 제공',
     'SERVE',
     'DB에 적재된 메타데이터와 리니지 흐름을 Spring API를 통해 프론트엔드 화면에 표시한다.',
     4);
