DROP TABLE IF EXISTS gov_integrated_meta_column;
DROP TABLE IF EXISTS gov_integrated_meta_section_field;
DROP TABLE IF EXISTS gov_integrated_meta_section;
DROP TABLE IF EXISTS gov_integrated_meta;
DROP TABLE IF EXISTS portal_menu;
DROP TABLE IF EXISTS portal_permission_assignment;
DROP TABLE IF EXISTS portal_iam_role;
DROP TABLE IF EXISTS portal_permission;
DROP TABLE IF EXISTS gov_access_request_history;
DROP TABLE IF EXISTS gov_ref_board;
DROP TABLE IF EXISTS gov_ref_form_item;
DROP TABLE IF EXISTS gov_access_request;
DROP TABLE IF EXISTS gov_ai_agent_mapping;
DROP TABLE IF EXISTS gov_pipeline_run;
DROP TABLE IF EXISTS gov_asset_catalog;
DROP TABLE IF EXISTS sample_jpa;
DROP TABLE IF EXISTS sample;

CREATE TABLE sample (
    sample_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_name VARCHAR(200) NOT NULL,
    description VARCHAR(1000)
);

CREATE TABLE sample_jpa (
    sample_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_name VARCHAR(200) NOT NULL,
    description VARCHAR(1000)
);

CREATE TABLE portal_permission (
    permission_code VARCHAR(80) PRIMARY KEY,
    permission_name VARCHAR(120) NOT NULL,
    permission_type VARCHAR(30) NOT NULL,
    target_key      VARCHAR(120) NOT NULL,
    action_code     VARCHAR(30) NOT NULL,
    description     VARCHAR(1000)
);

CREATE TABLE portal_menu (
    menu_id         VARCHAR(80) PRIMARY KEY,
    parent_menu_id  VARCHAR(80),
    menu_name       VARCHAR(120) NOT NULL,
    route_path      VARCHAR(300),
    permission_code VARCHAR(80),
    sort_order      INT DEFAULT 0 NOT NULL,
    visible         BOOLEAN DEFAULT TRUE NOT NULL,
    enabled         BOOLEAN DEFAULT TRUE NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    CONSTRAINT fk_portal_menu_parent_menu FOREIGN KEY (parent_menu_id) REFERENCES portal_menu(menu_id),
    CONSTRAINT fk_portal_menu_permission_code FOREIGN KEY (permission_code) REFERENCES portal_permission(permission_code),
    CONSTRAINT uq_portal_menu_route UNIQUE (route_path)
);

CREATE INDEX idx_portal_menu_parent ON portal_menu(parent_menu_id, sort_order);
CREATE INDEX idx_portal_menu_permission ON portal_menu(permission_code);

CREATE TABLE portal_iam_role (
    role_code           VARCHAR(50) PRIMARY KEY,
    role_name           VARCHAR(100) NOT NULL,
    external_group_name VARCHAR(200) NOT NULL,
    description         VARCHAR(1000)
);

CREATE TABLE portal_permission_assignment (
    assignment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_type    VARCHAR(20) NOT NULL,
    subject_id      VARCHAR(200) NOT NULL,
    subject_name    VARCHAR(200) NOT NULL,
    permission_code VARCHAR(80) NOT NULL,
    allowed         BOOLEAN DEFAULT TRUE NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    CONSTRAINT fk_portal_permission_assignment FOREIGN KEY (permission_code) REFERENCES portal_permission(permission_code),
    CONSTRAINT uq_portal_permission_assignment UNIQUE (subject_type, subject_id, permission_code)
);

CREATE TABLE gov_asset_catalog (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id         VARCHAR(80) NOT NULL UNIQUE,
    asset_name       VARCHAR(200) NOT NULL,
    asset_stage      VARCHAR(30) NOT NULL,
    asset_kind       VARCHAR(80) NOT NULL,
    source_system    VARCHAR(80) NOT NULL,
    storage_location VARCHAR(500),
    owner_name       VARCHAR(100) NOT NULL,
    steward_name     VARCHAR(100),
    classification   VARCHAR(50) NOT NULL,
    mnpi             BOOLEAN DEFAULT FALSE NOT NULL,
    pii              BOOLEAN DEFAULT FALSE NOT NULL,
    domain_name      VARCHAR(80) NOT NULL,
    description      VARCHAR(1000),
    lifecycle_status VARCHAR(30) NOT NULL,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP NOT NULL
);

CREATE TABLE gov_pipeline_run (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_name    VARCHAR(200) NOT NULL,
    recipe_id        VARCHAR(100) NOT NULL,
    recipe_version   VARCHAR(30) NOT NULL,
    dataiku_run_id   VARCHAR(100) NOT NULL,
    source_asset_id  VARCHAR(80),
    target_asset_id  VARCHAR(80),
    process_stage    VARCHAR(30) NOT NULL,
    status           VARCHAR(30) NOT NULL,
    processed_count  BIGINT DEFAULT 0 NOT NULL,
    quality_score    DECIMAL(5, 2),
    duration_seconds INT,
    started_at       TIMESTAMP NOT NULL,
    ended_at         TIMESTAMP,
    CONSTRAINT fk_pipeline_source_asset FOREIGN KEY (source_asset_id) REFERENCES gov_asset_catalog(asset_id),
    CONSTRAINT fk_pipeline_target_asset FOREIGN KEY (target_asset_id) REFERENCES gov_asset_catalog(asset_id)
);

CREATE TABLE gov_ai_agent_mapping (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name         VARCHAR(120) NOT NULL,
    dataset_asset_id   VARCHAR(80) NOT NULL,
    permission_level   VARCHAR(50) NOT NULL,
    status             VARCHAR(30) NOT NULL,
    last_used_at       TIMESTAMP,
    today_access_count BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT fk_agent_dataset FOREIGN KEY (dataset_asset_id) REFERENCES gov_asset_catalog(asset_id)
);

CREATE TABLE gov_access_request (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_title  VARCHAR(200) NOT NULL,
    request_type   VARCHAR(50) NOT NULL,
    requester_name VARCHAR(80) NOT NULL,
    requester_team VARCHAR(120) NOT NULL,
    summary        VARCHAR(1000) NOT NULL,
    status         VARCHAR(30) NOT NULL,
    target_date    DATE,
    priority       VARCHAR(30),
    submitted_at   TIMESTAMP NOT NULL,
    decided_at     TIMESTAMP
);

CREATE TABLE gov_access_request_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id  BIGINT NOT NULL,
    from_status VARCHAR(30),
    to_status   VARCHAR(30) NOT NULL,
    actor_name  VARCHAR(80) NOT NULL,
    comment     VARCHAR(1000),
    occurred_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_request_history FOREIGN KEY (request_id) REFERENCES gov_access_request(id)
);

CREATE TABLE gov_ref_form_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    category    VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    target_date DATE,
    priority    VARCHAR(30)
);

CREATE TABLE gov_ref_board (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                   VARCHAR(200) NOT NULL,
    category                VARCHAR(50) NOT NULL,
    writer_name             VARCHAR(50) NOT NULL,
    content                 VARCHAR(4000) NOT NULL,
    attachment_id           VARCHAR(36),
    attachment_file_name    VARCHAR(255),
    attachment_size         BIGINT,
    attachment_content_type VARCHAR(255),
    attachment_download_url VARCHAR(500),
    view_count              INT DEFAULT 0 NOT NULL,
    created_at              TIMESTAMP NOT NULL,
    updated_at              TIMESTAMP NOT NULL
);

CREATE TABLE gov_integrated_meta (
    meta_id          VARCHAR(40) PRIMARY KEY,
    meta_type        VARCHAR(30) NOT NULL,
    meta_name        VARCHAR(200) NOT NULL,
    asset_kind       VARCHAR(100) NOT NULL,
    source_system    VARCHAR(80) NOT NULL,
    owner_department VARCHAR(100) NOT NULL,
    security_level   VARCHAR(50) NOT NULL,
    updated_at       TIMESTAMP NOT NULL
);

CREATE TABLE gov_integrated_meta_section (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_id       VARCHAR(40) NOT NULL,
    section_id    VARCHAR(40) NOT NULL,
    title         VARCHAR(100) NOT NULL,
    display_order INT NOT NULL,
    CONSTRAINT fk_meta_section FOREIGN KEY (meta_id) REFERENCES gov_integrated_meta(meta_id)
);

CREATE TABLE gov_integrated_meta_section_field (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_pk    BIGINT NOT NULL,
    field_key     VARCHAR(100) NOT NULL,
    field_value   VARCHAR(1000),
    display_order INT NOT NULL,
    CONSTRAINT fk_meta_section_field FOREIGN KEY (section_pk) REFERENCES gov_integrated_meta_section(id)
);

CREATE TABLE gov_integrated_meta_column (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_id        VARCHAR(40) NOT NULL,
    ordinal        INT NOT NULL,
    column_name    VARCHAR(100) NOT NULL,
    data_type      VARCHAR(100) NOT NULL,
    nullable_yn    VARCHAR(1) NOT NULL,
    key_type       VARCHAR(30) NOT NULL,
    security_level VARCHAR(50) NOT NULL,
    description    VARCHAR(500),
    CONSTRAINT fk_meta_column FOREIGN KEY (meta_id) REFERENCES gov_integrated_meta(meta_id)
);
