DROP TABLE IF EXISTS lineage_flow;
DROP TABLE IF EXISTS metadata_catalog;
DROP TABLE IF EXISTS hira_institution_sample;

CREATE TABLE hira_institution_sample (
    sample_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encrypted_provider_id VARCHAR(300) NOT NULL,
    institution_name      VARCHAR(300) NOT NULL,
    institution_type      VARCHAR(100),
    sido_name             VARCHAR(100),
    sigungu_name          VARCHAR(100),
    road_address          VARCHAR(600),
    specialty_name        VARCHAR(150),
    opened_date           DATE
);

CREATE TABLE metadata_catalog (
    metadata_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_name     VARCHAR(200) NOT NULL,
    dataset_type     VARCHAR(40)  NOT NULL,
    source_name      VARCHAR(150),
    storage_location VARCHAR(500),
    row_count        BIGINT DEFAULT 0,
    columns_summary  VARCHAR(1000),
    description      VARCHAR(1000)
);

CREATE TABLE lineage_flow (
    flow_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name    VARCHAR(200) NOT NULL,
    source_type    VARCHAR(40)  NOT NULL,
    target_name    VARCHAR(200) NOT NULL,
    target_type    VARCHAR(40)  NOT NULL,
    process_name   VARCHAR(200) NOT NULL,
    transform_type VARCHAR(60)  NOT NULL,
    description    VARCHAR(1000),
    sort_order     INT          NOT NULL
);
